### ISSUE TITLE
Voltage Sequencer - Stage selected vs All gates

### ISSUE THREAD

**Issue by Kwurqx** [nullJaX/vcvrack-patchable-devices#3]
Hi,

I checked out your Patchable Devices modules in VCV Rack. Great stuff.

Voltage sequencer has an output labeled Stage selected, but also All gates. I expected it to give me all gates for active steps.

Suggestion: Add an option to (also) output a gate for each step with a Voltage other the zero (0 Volt). So the All gates output could be used to provide a per step gate. Also: add gate length? So for steps with a gate length smaller then 100% we would get 2 gates instead of a continous gate. If small enough, you would in effect get a Trigger.

**Comment by nullJaX** [comment]
Hi,

The `Stage Selected` output indicates only that any of the 8 stages has been selected/requested with a push button or a `Select Jack` (first line of jacks just above knobs). However, the output gates indicate which of the sequencer's stage is currently active.

I also highly value the suggestion, however I would like to keep these modules as simple as possible. As a workaround, you can achieve the same result with additional modules, for instance (the envelope generator used should have a trigger input):
```
Clock ------------------------------------> Envelope Generator -----------------------> VCA ------>
      \                 /--------------------------/                                    /
       \               / (row A used as Envelope Time parameters)                      /
        \--> Sequencer --------------------------------------------> Comparator ------/
                         (row B used to mark stages 'active')
```

Thanks for a feedback.
